name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build SvelteKit app
        run: |
          npm install
          npm run build
      
      - name: Deploy to main
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: "admin"
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          source: "build/*"
          target: "/home/admin/wwwryulang"
          strip_components: 1
          